services:
  - type: web
    name: nexusbot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --workers 1 --threads 4 --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_SECRET
        sync: false
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_TELEGRAM_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: "8000"
      - key: FIREBASE_URL
        sync: false
      - key: FIREBASE_SECRET
        sync: false
